# CREATE DATABASE `mapspot-on-rails-development` CHARACTER SET utf8 COLLATE utf8_general_ci 

development:
    adapter:  mysql2 
    database: german-week-dev
    username: root
    password: asdfg
    encoding: utf8
    #host: 192.168.1.200
    #port: 3306
    host: 127.0.0.1
    socket: /tmp/mysql.sock
    reconnect: true
    pool: 5

production:
    adapter:  mysql2
    database: german-week-prod
    username: german-week
    password: german-week
    encoding: utf8
    #host: 192.168.1.200
    host: 127.0.0.1
    socket: /tmp/mysql.sock
    #port: 3306
    reconnect: true
    pool: 5

